services:
  - type: web
    name: ppd
    runtime: static
    buildCommand: npm i -g pnpm && pnpm install && pnpm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
